services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Kollmeier\ContaoIsotopePaypalSDKBundle\:
        resource: '../../*'
        exclude: '../../{Resources,DependencyInjection,Entity,Tests,Kernel.php}'

    Kollmeier\ContaoIsotopePaypalSDKBundle\Controller\:
        resource: '../../Controller/*'
        tags: [ controller.service_arguments ]

    Kollmeier\ContaoIsotopePaypalSDKBundle\EventListener\DataContainer\IsoPaymentListener:
        public: true
        tags:
#            - { name: 'contao.callback', table: 'tl_iso_payment', target: 'fields.paypalSDKIsSandbox.load', priority: -1 }
#            - { name: 'contao.callback', table: 'tl_iso_payment', target: 'fields.paypalSDKIsSandbox.save', priority: -1 }
#            - { name: 'contao.callback', table: 'tl_iso_payment', target: 'fields.paypalSDKNoSandbox.save' }
#            - { name: 'contao.callback', table: 'tl_iso_payment', target: 'fields.paypalSDKNoSandbox.input_field' }

    Kollmeier\ContaoIsotopePaypalSDKBundle\EventListener\ReplaceInsertTagsListener:
        public: true
